- yum:
    name: nginx
    state: present
  when: ansible_distribution == "RedHat"

- apt:
    name: nginx
    state: present
  when: ansible_distribution == "Ubuntu"

- firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes
  when: ansible_distribution == "RedHat"

- file:
    path: /usr/share/nginx/html
    state: directory
    mode: "0755"
  when: ansible_distribution == "RedHat"

- file:
    path: /var/www/html
    state: directory
    mode: "0755"
  when: ansible_distribution == "Ubuntu"

- template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  when: ansible_distribution == "RedHat"

- template:
    src: index.html.j2
    dest: /var/www/html/index.html
  when: ansible_distribution == "Ubuntu"

- service:
    name: nginx
    state: restarted
